version: "3.9"

services:

  db:
    image: postgres:13.2-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    command: sh -c "
      poetry run python -m manage migrate
      && poetry run gunicorn -b 0.0.0.0 web_calculator.wsgi --reload
      "
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data:

