version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/12/main:/var/lib/postgresql/data
      #- volume_for_postgresql_db:/var/lib/postgresql/data
      #- ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: poetry run python -m manage runserver 0.0.0.0:8000
    volumes:
      - .:/app/_data
    ports:
      - "8000:8000"
    depends_on:
      - db
