# Generated by Django 2.2.4 on 2020-04-07 17:23

import calculator.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20191026_1149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exp',
            managers=[
                ('exprassions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='exp',
            name='exp',
            field=models.CharField(db_index=True, max_length=150, verbose_name='exprassion'),
        ),
        migrations.AlterField(
            model_name='exp',
            name='result_of_exp',
            field=models.CharField(blank=True, db_index=True, max_length=150, validators=[calculator.validators.validate_result_of_exp], verbose_name='result of exprassion'),
        ),
    ]
