# Generated by Django 2.2.4 on 2020-04-24 14:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20200407_1723'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exp',
            managers=[
                ('expressions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='exp',
            name='exp',
            field=models.CharField(db_index=True, max_length=150, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='exp',
            name='result_of_exp',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='result of expression'),
        ),
    ]
