# Generated by Django 3.1.4 on 2021-03-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20210330_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='date',
            new_name='created_at',
        ),
    ]
