# Generated by Django 3.1.4 on 2021-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20201116_1650'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='exp',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='exp',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='exp',
            name='expression',
            field=models.CharField(max_length=150, verbose_name='expression'),
        ),
        migrations.AlterField(
            model_name='exp',
            name='result_of_expression',
            field=models.CharField(blank=True, max_length=150, verbose_name='result of expression'),
        ),
    ]
