# Generated by Django 3.1.4 on 2021-04-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20210330_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exp',
            new_name='Expression',
        ),
    ]
